-- =============================================================================
-- 05_load.sql — load the seed. Generated by make_seed.sh on 2026-09-05T03:31:01Z.
--
-- A DATED SNAPSHOT OF REAL PRODUCTION ROWS, FOR LOCAL DEVELOPMENT.
-- Not fabricated · not authoritative · not a source of truth · not test data.
-- REGENERATE, NEVER EDIT.
--
-- Run against an EMPTY database that already has 01_schema.sql loaded.
-- =============================================================================
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _party        (LIKE party)         ON COMMIT DROP;
CREATE TEMP TABLE _content_claim(LIKE content_claim) ON COMMIT DROP;
CREATE TEMP TABLE _party_event  (LIKE party_event)   ON COMMIT DROP;

\copy _party(id, prefix, gln, legal_name, city, country, mo, lei, state, source, exception_reason, verified_at, first_seen, last_updated, duns, is_demo, demo_urn, licence_type, licence_type_source, url, url_source, stage_ancestor, name_fold) from '02_party.csv' csv header
\copy _content_claim(id, party_id, pillar, section, display_order, nm, identifier, grade, tx, doc_key, first_seen, last_updated) from '03_content_claim.csv' csv header
\copy _party_event(id, party_id, event_type, from_state, to_state, detail, source, actor, at) from '04_party_event.csv' csv header

-- party first: content_claim and party_event carry FKs to it.
INSERT INTO party (id, prefix, gln, legal_name, city, country, mo, lei, state, source, exception_reason, verified_at, first_seen, last_updated, duns, is_demo, demo_urn, licence_type, licence_type_source, url, url_source, stage_ancestor, name_fold)
  OVERRIDING SYSTEM VALUE SELECT id, prefix, gln, legal_name, city, country, mo, lei, state, source, exception_reason, verified_at, first_seen, last_updated, duns, is_demo, demo_urn, licence_type, licence_type_source, url, url_source, stage_ancestor, name_fold FROM _party;
INSERT INTO content_claim (id, party_id, pillar, section, display_order, nm, identifier, grade, tx, doc_key, first_seen, last_updated)
  OVERRIDING SYSTEM VALUE SELECT id, party_id, pillar, section, display_order, nm, identifier, grade, tx, doc_key, first_seen, last_updated FROM _content_claim;
INSERT INTO party_event (id, party_id, event_type, from_state, to_state, detail, source, actor, at)
  OVERRIDING SYSTEM VALUE SELECT id, party_id, event_type, from_state, to_state, detail, source, actor, at FROM _party_event;

-- Explicit ids do not move the sequence. Without this the next insert collides.
SELECT setval(pg_get_serial_sequence('party','id'),
              (SELECT max(id) FROM party));
SELECT setval(pg_get_serial_sequence('content_claim','id'),
              (SELECT max(id) FROM content_claim));
SELECT setval(pg_get_serial_sequence('party_event','id'),
              (SELECT max(id) FROM party_event));

COMMIT;
