#!/usr/bin/env bash
# =============================================================================
# make_seed.sh — generate the disposable dev seed from thingdaddy_population.
#
#   RUN ON THE MAC MINI, where production lives.
#   cd ~/thingdaddy/population && ./seed/make_seed.sh
#
# READ ONLY against production. It runs SELECTs and pg_dump --schema-only.
# It writes only into its own directory.
#
# Produces population/seed/ :
#   01_schema.sql  02_party.csv  03_content_claim.csv  04_party_event.csv
#   05_load.sql    MANIFEST.txt  README.md
#
# THE SEED IS DISPOSABLE. When claims are re-keyed to prefix, delete the
# directory and run this again. Do not migrate it. Do not edit its rows.
# =============================================================================
set -euo pipefail

SRC_DB="${SRC_DB:-thingdaddy_population}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARTIES="4153997,4090838,4090839,4090847"
TAKEN="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

say() { printf '  %s\n' "$*"; }
die() { printf '\n  REFUSED: %s\n\n' "$*" >&2; exit 1; }

echo
echo "make_seed  $TAKEN"
echo "  source: $SRC_DB  (read only)"
echo "  target: $HERE"
echo "  parties: $PARTIES"
echo

# ── preflight ────────────────────────────────────────────────────────────────
# Refuse before writing anything, not halfway through.
command -v psql    >/dev/null || die "psql not on PATH"
command -v pg_dump >/dev/null || die "pg_dump not on PATH"
psql -qAt -d "$SRC_DB" -c 'select 1' >/dev/null 2>&1 \
  || die "cannot connect to $SRC_DB"

N_PARTY=$(psql -qAt -d "$SRC_DB" -c "select count(*) from party where id in ($PARTIES);")
[ "$N_PARTY" = "4" ] || die "expected 4 parties, found $N_PARTY. The ids moved — re-read them before regenerating."

echo "PREFLIGHT"
say "psql, pg_dump present"
say "connected to $SRC_DB"
say "all 4 party ids present"
echo

# ── column lists, read from the database not typed ───────────────────────────
# search_tsv is excluded by TYPE, not by name: trg_party_search_tsv rebuilds it
# on INSERT, and carrying a stale tsvector would be a value we did not derive.
cols_of() {
  psql -qAt -d "$SRC_DB" -c "
    select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    from information_schema.columns
    where table_schema='public' and table_name='$1' and data_type <> 'tsvector';"
}

PARTY_COLS=$(cols_of party)
CLAIM_COLS=$(cols_of content_claim)
EVENT_COLS=$(cols_of party_event)

[ -n "$PARTY_COLS" ] || die "could not read party's columns"

# ── 01 schema ────────────────────────────────────────────────────────────────
echo "SCHEMA"
pg_dump --schema-only --no-owner --no-privileges -d "$SRC_DB" > "$HERE/01_schema.sql"
say "01_schema.sql  $(wc -l < "$HERE/01_schema.sql" | tr -d ' ') lines"

# ── 02-04 data ───────────────────────────────────────────────────────────────
echo
echo "DATA"
psql -qAt -d "$SRC_DB" <<SQL
\copy (select $PARTY_COLS from party where id in ($PARTIES) order by id) to '$HERE/02_party.csv' csv header
\copy (select $CLAIM_COLS from content_claim where party_id in ($PARTIES) order by party_id, pillar, display_order, id) to '$HERE/03_content_claim.csv' csv header
\copy (select $EVENT_COLS from party_event where party_id in ($PARTIES) order by id) to '$HERE/04_party_event.csv' csv header
SQL

# Counts read BACK FROM THE FILES, never from the query that wrote them.
# A count taken from the query cannot report a truncated write.
rows_in() { echo $(( $(wc -l < "$1") - 1 )); }
N_P=$(rows_in "$HERE/02_party.csv")
N_C=$(rows_in "$HERE/03_content_claim.csv")
N_E=$(rows_in "$HERE/04_party_event.csv")

say "02_party.csv          $N_P rows"
say "03_content_claim.csv  $N_C rows"
say "04_party_event.csv    $N_E rows"

[ "$N_P" = "4" ] || die "party.csv holds $N_P rows, expected 4"
[ "$N_C" -gt 0 ] || die "content_claim.csv is empty — the seed would show four blank ThingSites"

# ── 05 load ──────────────────────────────────────────────────────────────────
# Loaded via TEMP table + INSERT ... OVERRIDING SYSTEM VALUE.
# party.id and content_claim.id are GENERATED ALWAYS AS IDENTITY. Whether COPY
# accepts an explicit identity value is not something to rely on — this path
# works either way, and it is the same trick stage_to_production.py uses.
# If the ids do not travel, every claim loses its party.
cat > "$HERE/05_load.sql" <<SQL
-- =============================================================================
-- 05_load.sql — load the seed. Generated by make_seed.sh on $TAKEN.
--
-- A DATED SNAPSHOT OF REAL PRODUCTION ROWS, FOR LOCAL DEVELOPMENT.
-- Not fabricated · not authoritative · not a source of truth · not test data.
-- REGENERATE, NEVER EDIT.
--
-- Run against an EMPTY database that already has 01_schema.sql loaded.
-- =============================================================================
\\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _party        (LIKE party)         ON COMMIT DROP;
CREATE TEMP TABLE _content_claim(LIKE content_claim) ON COMMIT DROP;
CREATE TEMP TABLE _party_event  (LIKE party_event)   ON COMMIT DROP;

\\copy _party($PARTY_COLS) from '02_party.csv' csv header
\\copy _content_claim($CLAIM_COLS) from '03_content_claim.csv' csv header
\\copy _party_event($EVENT_COLS) from '04_party_event.csv' csv header

-- party first: content_claim and party_event carry FKs to it.
INSERT INTO party ($PARTY_COLS)
  OVERRIDING SYSTEM VALUE SELECT $PARTY_COLS FROM _party;
INSERT INTO content_claim ($CLAIM_COLS)
  OVERRIDING SYSTEM VALUE SELECT $CLAIM_COLS FROM _content_claim;
INSERT INTO party_event ($EVENT_COLS)
  OVERRIDING SYSTEM VALUE SELECT $EVENT_COLS FROM _party_event;

-- Explicit ids do not move the sequence. Without this the next insert collides.
SELECT setval(pg_get_serial_sequence('party','id'),
              (SELECT max(id) FROM party));
SELECT setval(pg_get_serial_sequence('content_claim','id'),
              (SELECT max(id) FROM content_claim));
SELECT setval(pg_get_serial_sequence('party_event','id'),
              (SELECT max(id) FROM party_event));

COMMIT;
SQL
say "05_load.sql written"

# ── MANIFEST ─────────────────────────────────────────────────────────────────
cat > "$HERE/MANIFEST.txt" <<MAN
A DATED SNAPSHOT OF REAL PRODUCTION ROWS, FOR LOCAL DEVELOPMENT.

  taken        $TAKEN
  source       $SRC_DB on the Mac mini
  generator    make_seed.sh
  parties      $PARTIES

  party            $N_P
  content_claim    $N_C
  party_event      $N_E

seed_up.sh checks the loaded database against these three numbers and fails
loudly on a mismatch. A silent partial load renders an empty screen and looks
like a bug in the screens.

REGENERATE, NEVER EDIT. If this file is more than a week old, remake the seed.
A stale seed that still loads is worse than one that fails, because it looks
current.
MAN
say "MANIFEST.txt written"

# ── README ───────────────────────────────────────────────────────────────────
cat > "$HERE/README.md" <<'DOC'
# The dev seed

```
A DATED SNAPSHOT OF REAL PRODUCTION ROWS, FOR LOCAL DEVELOPMENT.

NOT fabricated. These are real GS1 prefixes with real GUDID provenance.
NOT authoritative. thingdaddy_population on the Mac mini is the record.
NOT a source of truth. Nothing here flows back.
NOT test data. Do not edit rows to make something render.

REGENERATE, NEVER EDIT. Cheap to remake, expensive to trust.
```

See `MANIFEST.txt` for the date and the row counts as taken.

## Bring it up

```
createdb thingdaddy_population
./seed_up.sh
cd ../api && npm install && npm start
```

Then open `population/fill/td_screens_live.html` in a browser.

The database is named `thingdaddy_population` so `api/.env` needs no change.
You will also need `INGEST_TOKEN` in `.env` if you touch a write endpoint —
though nothing in this seed exercises one.

## What is in it

| party_id | prefix | company | state | claims |
|---|---|---|---|---|
| 4090847 | 081627002 | Illumina, Inc. | **verified** | 88 |
| 4090838 | 081577302 | Thermo Fisher Scientific (Asheville) LLC | **verified** | 70 |
| 4090839 | 081693402 | Thermo Fisher Scientific (Asheville) LLC | **verified** | 15 |
| 4153997 | 0817089 | DIAZYME LABORATORIES, INC. | candidate | 14 |

Thermo Fisher Asheville holds two prefixes on two rows. That is
one-prefix-one-ThingSite, correct, carried as found.

## What is EMPTY, and why that is not a bug

```
node (for these parties)   0     92,678 nodes exist; none backfilled here
association               0
asset · edge · content_doc · party_origin   0
```

**This is production's current state, not a gap in the seed.** The same
endpoints return the same emptiness on the Mac mini today.

`/node/by-legacy/party/:id` returns 404 by design. From the API's own source:
*"404 when the spine hasn't been backfilled for this party (honest — the UI
shows 'not on the spine yet', never fakes a node)."*

So the graph and association screens show the empty state deliberately.

## Three more things that are correct, not broken

**`/stats` returns 4.** It counts the whole database and the database has four
parties.

**S1 shows "Over 11,000,000 identities".** A hardcoded string, not from
`/stats`. Flagged in PR #17 finding 3 and marked TODO on the Open list. It will
read eleven million over a four-row database. Unruled.

**`const RECORDS` still exists at line 285 of `td_screens_live.html`.** The file
is a hybrid — some screens call the API, some still read the fixture. Pointing
the remaining paths at the API is an open item.

## Endpoints this seed serves

```
/health · /stats · /search?q= · /verified
/record/:id · /record/prefix/:prefix
/party/:id/completeness
/party/:id/epcis · /party/:id/assets     served, empty
/node/by-legacy/party/:id                404, honest, by design
```

Write endpoints are not exercised. `/gate/:id` additionally needs
`population/verify/verify_cli.py`, which is not in git.

## Disposal

This seed dies when claims are re-keyed to prefix under the 4 September ruling.
Regenerate — do not migrate it, do not edit it, do not write tooling that
assumes its shape.
DOC
say "README.md written"

echo
echo "DONE. $((N_P + N_C + N_E)) rows total."
echo "  Commit the directory, or hand it over as a tarball."
echo "  Nothing was written to $SRC_DB."
echo
